'use client';
import {FormEvent,useState} from 'react';
import Link from 'next/link';
import {useRouter} from 'next/navigation';
import {motion} from 'framer-motion';
import {ArrowRight,Lock,Mail,ShieldCheck} from 'lucide-react';
import {PairLogo} from '@/components/ui/pair-logo';
import {AuthBackground} from './auth-background';
import {useAuth} from '@/hooks/use-auth';

export function SignupForm(){
 const router=useRouter();const {signup}=useAuth();const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 async function submit(e:FormEvent){e.preventDefault();setError('');if(password.length<8){setError('Password must be at least 8 characters.');return}if(password!==confirm){setError('Passwords do not match.');return}setBusy(true);try{await signup(email,password);router.push('/app')}catch(err){setError(err instanceof Error?err.message:'Unable to create account.')}finally{setBusy(false)}}
 return <div className="relative min-h-screen chassis flex items-center justify-center px-5 py-12"><AuthBackground/><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} className="relative z-10 w-full max-w-md"><div className="industrial-panel rounded-[28px] p-7 md:p-9"><Link href="/" className="inline-flex"><PairLogo size={42}/></Link><div className="mt-9"><p className="technical text-[9px] font-bold text-accent">AUTH / 02</p><h1 className="mt-2 text-3xl font-extrabold tracking-[-.035em]">Create workspace.</h1><p className="mt-2 text-sm leading-6 text-slate">Create your PAIR account to start a bid review.</p></div>{error&&<div className="mt-5 rounded-xl border border-red-300 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}<form onSubmit={submit} className="mt-7 space-y-5"><label className="block text-sm font-bold">Email<input className="industrial-input mt-2" required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@organisation.gov.in"/></label><label className="block text-sm font-bold">Password<input className="industrial-input mt-2" required type="password" minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Minimum 8 characters"/></label><label className="block text-sm font-bold">Confirm password<input className="industrial-input mt-2" required type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repeat password"/></label><p className="text-xs leading-5 text-slate">By continuing, you agree that PAIR is an AI-assisted decision-support tool and not the final procurement authority.</p><button disabled={busy} className="industrial-button industrial-button-accent w-full rounded-xl py-3 text-sm font-extrabold">{busy?'CREATING…':'CREATE ACCOUNT'}{!busy&&<ArrowRight size={16}/>}</button></form><div className="mt-6 flex items-center gap-2 text-[10px] font-mono text-slate"><ShieldCheck size={14} className="text-emerald-600"/> Server-side account creation</div><p className="mt-7 text-center text-sm text-slate">Already registered? <Link href="/login" className="font-extrabold text-accent hover:underline">Sign in</Link></p></div></motion.div></div>
}
