'use client';
import {ChangeEvent,useEffect,useMemo,useState} from 'react';
import {motion} from 'framer-motion';
import {AlertTriangle,CheckCircle2,ChevronRight,FileText,Loader2,RefreshCw,Search,ShieldCheck,Sparkles,Upload,XCircle} from 'lucide-react';
import {apiFetch} from '@/lib/api';
import {DocumentItem,Evidence,Project,Requirement,Summary} from '@/lib/types';
import {IndustrialPanel,StatusLED,TechnicalLabel} from '@/components/ui/industrial';

type Result={id:number;project_id:number;requirement_id:number;evidence_id:number|null;status:string;explanation:string|null;confidence:number|null;created_at:string|null};

const meta:Record<string,{label:string;cls:string;Icon:any}>={
 compliant:{label:'COMPLIANT',cls:'text-emerald-700 bg-emerald-50 border-emerald-200',Icon:CheckCircle2},
 partial:{label:'PARTIAL',cls:'text-amber-700 bg-amber-50 border-amber-200',Icon:AlertTriangle},
 non_compliant:{label:'NON-COMPLIANT',cls:'text-red-700 bg-red-50 border-red-200',Icon:XCircle},
 needs_review:{label:'NEEDS REVIEW',cls:'text-amber-700 bg-amber-50 border-amber-200',Icon:AlertTriangle},
 insufficient_data:{label:'INSUFFICIENT DATA',cls:'text-slate bg-slate-100 border-slate-200',Icon:Search}
};

export default function ProjectPage({params}:{params:{id:string}}){
 const id=Number(params.id);const [project,setProject]=useState<Project|null>(null);const [docs,setDocs]=useState<DocumentItem[]>([]);const [reqs,setReqs]=useState<Requirement[]>([]);const [evidence,setEvidence]=useState<Evidence[]>([]);const [results,setResults]=useState<Record<number,Result>>({});const [summary,setSummary]=useState<Summary|null>(null);const [selected,setSelected]=useState<number|null>(null);const [filter,setFilter]=useState('all');const [search,setSearch]=useState('');const [type,setType]=useState<'tender'|'vendor'>('tender');const [file,setFile]=useState<File|null>(null);const [busy,setBusy]=useState('');const [error,setError]=useState('');const [recommendation,setRecommendation]=useState('');
 async function load(){setBusy('load');setError('');try{const [p,d,r,e,res,s]=await Promise.all([apiFetch<Project>(`/api/v1/projects/${id}`),apiFetch<DocumentItem[]>(`/api/v1/projects/${id}/documents`),apiFetch<Requirement[]>(`/api/v1/projects/${id}/requirements`),apiFetch<Evidence[]>(`/api/v1/projects/${id}/evidence`),apiFetch<Result[]>(`/api/v1/compliance/projects/${id}/results`),apiFetch<Summary>(`/api/v1/compliance/projects/${id}/summary`)]);setProject(p);setDocs(d);setReqs(r);setEvidence(e);setSummary(s);const m:Record<number,Result>={};res.forEach(x=>m[x.requirement_id]=x);setResults(m);setSelected(x=>x??r[0]?.id??null)}catch(e){setError(e instanceof Error?e.message:'Unable to load review.')}finally{setBusy('')}}
 useEffect(()=>{if(Number.isFinite(id))load()},[id]);
 async function upload(){if(!file)return;setBusy('upload');setError('');try{const body=new FormData();body.append('file',file);const d=await apiFetch<DocumentItem>(`/api/v1/projects/${id}/documents?document_type=${type}`,{method:'POST',body});await apiFetch(`/api/v1/projects/${id}/documents/${d.id}/extract`,{method:'POST'});setFile(null);const el=document.getElementById('bid-file') as HTMLInputElement|null;if(el)el.value='';await load()}catch(e){setError(e instanceof Error?e.message:'Upload failed.')}finally{setBusy('')}}
 async function extract(doc:DocumentItem){setBusy(`extract-${doc.id}`);try{if(doc.document_type==='vendor')await apiFetch(`/api/v1/projects/${id}/documents/${doc.id}/extract-evidence?provider=nvidia`,{method:'POST'});else await apiFetch(`/api/v1/projects/${id}/documents/${doc.id}/extract-requirements?provider=nvidia`,{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:'AI extraction failed.')}finally{setBusy('')}}
 async function analyze(){setBusy('analyze');setError('');try{await apiFetch(`/api/v1/compliance/projects/${id}/analyze-all`,{method:'POST'});await load()}catch(e){setError(e instanceof Error?e.message:'Compliance analysis failed.')}finally{setBusy('')}}
 async function recommend(){setBusy('recommend');try{const r=await apiFetch<{recommendation:string}>(`/api/v1/compliance/recommendation?project_id=${id}`,{method:'POST'});setRecommendation(r.recommendation)}catch(e){setError(e instanceof Error?e.message:'Recommendation failed.')}finally{setBusy('')}}
 const visible=useMemo(()=>reqs.filter(r=>{const result=results[r.id];return (filter==='all'||result?.status===filter)&&`${r.title} ${r.requirement_text} ${r.category}`.toLowerCase().includes(search.toLowerCase())}),[reqs,results,filter,search]);
 const selectedReq=selected?reqs.find(r=>r.id===selected):undefined;const selectedResult=selectedReq?results[selectedReq.id]:undefined;const selectedEvidence=selectedResult?.evidence_id?evidence.find(e=>e.id===selectedResult.evidence_id):undefined;
 if(!project)return <div className="p-8 text-sm text-slate">{error||'Loading review…'}</div>;
 return <div className="mx-auto max-w-[1550px] px-4 py-6 md:px-7 md:py-8">
  <div className="flex flex-col gap-5 xl:flex-row xl:items-end xl:justify-between"><div><div className="flex flex-wrap items-center gap-3"><TechnicalLabel>REVIEW / PROJECT #{project.id}</TechnicalLabel><StatusLED label={project.status.toUpperCase()}/></div><h1 className="mt-3 max-w-4xl text-3xl font-extrabold tracking-[-.04em] md:text-4xl">{project.name}</h1><div className="mt-2 flex flex-wrap gap-4 text-xs text-slate"><span>GeM ID: <b className="font-mono text-ink">{project.gem_tender_id||'NOT SET'}</b></span><span>Created: <b className="font-mono text-ink">{new Date(project.created_at).toLocaleDateString()}</b></span></div></div><div className="flex gap-2"><button onClick={load} className="industrial-button rounded-xl bg-chassis p-3" aria-label="Refresh"><RefreshCw size={17}/></button><button onClick={analyze} disabled={!!busy||reqs.length===0} className="industrial-button industrial-button-accent inline-flex items-center gap-2 rounded-xl px-5 text-sm font-extrabold">{busy==='analyze'?<Loader2 size={15} className="animate-spin"/>:<ShieldCheck size={15}/>} {busy==='analyze'?'ANALYZING…':'RUN COMPLIANCE'}</button></div></div>
 {error&&<div className="mt-5 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</div>}
 <div className="mt-6 grid grid-cols-2 gap-4 lg:grid-cols-5">{[['SCORE',summary?.compliance_score!=null?`${summary.compliance_score}%`:'—'],['TOTAL',summary?.total_requirements??reqs.length],['COMPLIANT',summary?.compliant??0],['ATTENTION',(summary?.needs_review??0)+(summary?.insufficient_data??0)],['RISK',summary?.risk_level?.toUpperCase()||'PENDING']].map(([l,v])=><IndustrialPanel key={l as string} className="p-4"><TechnicalLabel>{l as string}</TechnicalLabel><p className={`mt-3 font-mono text-2xl font-bold ${l==='RISK'?(summary?.risk_level==='high'?'text-red-600':summary?.risk_level==='medium'?'text-amber-600':'text-emerald-700'):''}`}>{v as any}</p></IndustrialPanel>)}</div>
 <IndustrialPanel className="mt-6 p-5"><div className="flex flex-col gap-4 xl:flex-row xl:items-center xl:justify-between"><div><TechnicalLabel>DOCUMENT BAY / INPUT</TechnicalLabel><h2 className="mt-1 text-lg font-extrabold">Tender & bidder evidence</h2><p className="mt-1 text-xs text-slate">Upload PDF → extract text → run the relevant AI extraction.</p></div><div className="flex flex-col gap-2 sm:flex-row"><label className="industrial-recessed flex min-h-11 cursor-pointer items-center gap-2 rounded-xl px-3 text-xs font-bold text-slate"><Upload size={15} className="text-accent"/><span className="max-w-[240px] truncate">{file?.name||'Choose PDF'}</span><input id="bid-file" type="file" accept="application/pdf,.pdf" className="hidden" onChange={(e:ChangeEvent<HTMLInputElement>)=>setFile(e.target.files?.[0]||null)}/></label><select value={type} onChange={e=>setType(e.target.value as any)} className="industrial-input !min-h-11 !w-auto"><option value="tender">Tender / bid</option><option value="vendor">Bidder / vendor</option></select><button onClick={upload} disabled={!file||!!busy} className="industrial-button industrial-button-accent rounded-xl px-5 text-xs font-extrabold">{busy==='upload'?'UPLOADING…':'UPLOAD + EXTRACT'}</button></div></div><div className="mt-5 grid gap-3 md:grid-cols-2">{docs.length===0?<div className="industrial-recessed rounded-xl p-7 text-center text-xs text-slate md:col-span-2">No documents attached yet.</div>:docs.map(d=><div key={d.id} className="industrial-recessed rounded-xl p-4"><div className="flex items-start gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-[#2d3436] text-white shadow-sharp"><FileText size={17}/></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-extrabold">{d.filename}</p><p className="mt-1 font-mono text-[9px] uppercase text-slate">{d.document_type} · {d.page_count??'—'} pages · {d.extraction_status}</p></div><span className="technical text-[8px] text-slate">#{d.id}</span></div><div className="mt-4 flex items-center justify-between"><span className="text-[10px] text-slate">{Math.max(1,Math.round(d.file_size/1024))} KB</span>{(d.document_type==='vendor'||d.document_type==='tender'||d.document_type==='bid')&&<button disabled={!!busy||d.extraction_status!=='completed'} onClick={()=>extract(d)} className="rounded-lg bg-[#2d3436] px-3 py-2 text-[10px] font-bold text-white disabled:opacity-40">{busy===`extract-${d.id}`?'PROCESSING…':d.document_type==='vendor'?'EXTRACT EVIDENCE':'EXTRACT REQUIREMENTS'}</button>}</div></div>)}</div></IndustrialPanel>
 <div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_.75fr]"><IndustrialPanel className="overflow-hidden p-0"><div className="border-b border-slate/15 p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div><TechnicalLabel>COMPLIANCE MATRIX</TechnicalLabel><p className="mt-1 text-xs text-slate">{summary?.evaluated_requirements??0} of {summary?.total_requirements??reqs.length} evaluated</p></div><div className="industrial-recessed flex items-center gap-2 rounded-lg px-3"><Search size={15} className="text-slate"/><input className="h-10 w-64 max-w-full bg-transparent text-xs outline-none" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Filter requirements…"/></div></div><div className="mt-4 flex gap-2 overflow-x-auto">{['all','compliant','partial','needs_review','non_compliant','insufficient_data'].map(f=><button key={f} onClick={()=>setFilter(f)} className={`whitespace-nowrap rounded-lg px-3 py-2 text-[9px] font-bold uppercase ${filter===f?'bg-[#2d3436] text-white shadow-sharp':'bg-white/50 text-slate hover:bg-white'}`}>{f.replace(/_/g,' ')}</button>)}</div></div><div className="hidden grid-cols-[1.5fr_.6fr_.55fr_.7fr] border-b border-slate/10 px-5 py-3 text-[9px] font-mono font-bold uppercase tracking-wider text-slate md:grid"><span>Requirement</span><span>Evidence</span><span>Confidence</span><span>Status</span></div>{visible.length===0?<div className="p-14 text-center text-sm text-slate">No requirements match.</div>:visible.map(r=>{const res=results[r.id];const m=res?meta[res.status]:null;const M=m?.Icon;return <button key={r.id} onClick={()=>setSelected(r.id)} className={`grid w-full grid-cols-1 gap-3 border-b border-slate/10 px-5 py-4 text-left transition hover:bg-white/50 md:grid-cols-[1.5fr_.6fr_.55fr_.7fr] md:items-center ${selected===r.id?'bg-white/65':''}`}><div className="min-w-0"><div className="flex items-center gap-2"><span className="technical text-[8px] text-slate">REQ #{r.id}</span>{r.is_mandatory&&<span className="rounded bg-red-50 px-2 py-1 text-[8px] font-bold uppercase text-red-700">mandatory</span>}</div><p className="mt-1 truncate text-sm font-extrabold">{r.title}</p><p className="mt-1 line-clamp-1 text-[11px] text-slate">{r.requirement_text}</p></div><div className="font-mono text-[10px] text-slate">{res?.evidence_id?`#${res.evidence_id}`:'NONE'}</div><div className="font-mono text-[10px] text-slate">{res?.confidence!=null?`${Math.round(res.confidence*100)}%`:'—'}</div><div>{m?<span className={`inline-flex items-center gap-1 rounded-lg border px-2 py-1.5 text-[8px] font-bold ${m.cls}`}>{M&&<M size={11}/>} {m.label}</span>:<span className="technical text-[8px] text-slate">PENDING</span>}</div></button>})}</IndustrialPanel>
 <aside className="space-y-6"><IndustrialPanel className="overflow-hidden p-0"><div className="border-b border-slate/15 p-5"><TechnicalLabel>EVIDENCE INSPECTOR</TechnicalLabel><h2 className="mt-1 text-lg font-extrabold">Selected requirement</h2></div>{selectedReq?<div className="p-5"><h3 className="text-lg font-extrabold">{selectedReq.title}</h3><p className="mt-3 text-sm leading-6 text-slate">{selectedReq.requirement_text}</p><div className="mt-5 grid grid-cols-2 gap-3"><div className="industrial-recessed rounded-xl p-3"><TechnicalLabel>PAGE</TechnicalLabel><p className="mt-2 font-mono text-xs">{selectedReq.source_page_number??'—'}</p></div><div className="industrial-recessed rounded-xl p-3"><TechnicalLabel>CATEGORY</TechnicalLabel><p className="mt-2 truncate text-xs font-bold">{selectedReq.category}</p></div></div>{selectedEvidence?<div className="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4"><div className="flex items-center gap-2"><CheckCircle2 size={16} className="text-emerald-600"/><TechnicalLabel className="text-emerald-700">LINKED EVIDENCE</TechnicalLabel></div><p className="mt-3 text-sm leading-6 text-emerald-950">{selectedEvidence.evidence_text}</p><p className="mt-3 font-mono text-[9px] text-emerald-700">{selectedEvidence.evidence_type} · page {selectedEvidence.source_page_number??'—'} · {selectedEvidence.confidence!=null?`${Math.round(selectedEvidence.confidence*100)}% confidence`:''}</p></div>:<div className="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4"><TechnicalLabel className="text-amber-700">NO LINKED EVIDENCE</TechnicalLabel><p className="mt-2 text-xs leading-5 text-amber-900">No relevant evidence is currently linked to this requirement. Treat the finding as unresolved.</p></div>}{selectedResult&&<div className="mt-5 rounded-xl bg-[#2d3436] p-4 text-white"><TechnicalLabel className="text-white/50">AI ANALYSIS</TechnicalLabel><p className="mt-3 text-sm leading-6 text-white/75">{selectedResult.explanation||'No explanation returned.'}</p>{selectedResult.confidence!=null&&<div className="mt-4 border-t border-white/10 pt-3 font-mono text-[9px] text-white/50">CONFIDENCE / {Math.round(selectedResult.confidence*100)}%</div>}</div>}</div>:<div className="p-12 text-center text-sm text-slate">Select a requirement.</div>}</IndustrialPanel>
 <IndustrialPanel className="p-5"><div className="flex items-center justify-between"><div><TechnicalLabel>AI RECOMMENDATION</TechnicalLabel><h2 className="mt-1 text-lg font-extrabold">Decision support</h2></div><Sparkles size={18} className="text-accent"/></div><p className="mt-3 text-xs leading-5 text-slate">Generate an advisory summary after compliance analysis. It does not replace officer review.</p><button onClick={recommend} disabled={!!busy||!summary?.evaluated_requirements} className="industrial-button mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-chassis text-xs font-extrabold"><Sparkles size={14}/>{busy==='recommend'?'GENERATING…':'GENERATE RECOMMENDATION'}</button>{recommendation&&<div className="mt-4 whitespace-pre-wrap rounded-xl bg-[#2d3436] p-4 text-xs leading-6 text-white/75">{recommendation}</div>}</IndustrialPanel></aside></div>
 </div>
}
