'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {motion} from 'framer-motion';
import {Activity,ArrowRight,ClipboardCheck,FileCheck2,FolderOpen,Plus,ShieldAlert} from 'lucide-react';
import {apiFetch} from '@/lib/api';
import {useAuth} from '@/hooks/use-auth';
import {IndustrialPanel,StatusLED,TechnicalLabel} from '@/components/ui/industrial';
import {Project,Summary} from '@/lib/types';

export default function Dashboard(){
 const {user}=useAuth();const [projects,setProjects]=useState<Project[]>([]);const [summaries,setSummaries]=useState<Record<number,Summary>>({});const [loading,setLoading]=useState(true);
 useEffect(()=>{(async()=>{try{const d=await apiFetch<{projects:Project[]}>('/api/v1/projects');setProjects(d.projects);const pairs=await Promise.all(d.projects.slice(0,10).map(async p=>{try{return [p.id,await apiFetch<Summary>(`/api/v1/compliance/projects/${p.id}/summary`)] as const}catch{return [p.id,null] as const}}));setSummaries(Object.fromEntries(pairs.filter((x):x is [number,Summary]=>!!x[1])))}finally{setLoading(false)}})()},[]);
 const totals=useMemo(()=>{const s=Object.values(summaries);return {req:s.reduce((a,x)=>a+x.total_requirements,0),ok:s.reduce((a,x)=>a+x.compliant,0),attention:s.reduce((a,x)=>a+x.non_compliant+x.needs_review+x.insufficient_data,0),high:s.filter(x=>x.risk_level==='high').length}},[summaries]);
 const greeting=new Date().getHours()<12?'GOOD MORNING':new Date().getHours()<18?'GOOD AFTERNOON':'GOOD EVENING';
 return <div className="mx-auto max-w-[1450px] px-4 py-6 md:px-7 md:py-8">
  <div className="flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><TechnicalLabel>CONTROL ROOM / OVERVIEW</TechnicalLabel><h1 className="mt-2 text-3xl font-extrabold tracking-[-.04em] md:text-4xl">{greeting}, {user?.name||'OFFICER'}.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate">Your evidence-first procurement workspace. Monitor active reviews, unresolved findings and decision readiness.</p></div><Link href="/app/projects" className="industrial-button industrial-button-accent inline-flex w-fit items-center gap-2 rounded-xl px-5 py-3 text-sm font-extrabold uppercase"><Plus size={16}/> New bid review</Link></div>
  <div className="mt-7 grid grid-cols-2 gap-4 xl:grid-cols-4">{[['ACTIVE REVIEWS',projects.length,FolderOpen],['REQUIREMENTS',totals.req,FileCheck2],['COMPLIANT',totals.ok,ClipboardCheck],['ATTENTION',totals.attention,ShieldAlert]].map(([l,v,I])=>{const Icon=I as any;return <IndustrialPanel key={l as string} className="p-5"><div className="flex items-center justify-between"><TechnicalLabel>{l as string}</TechnicalLabel><Icon size={17} className="text-slate"/></div><p className="mt-5 font-mono text-3xl font-bold text-ink">{loading?'—':v as any}</p><div className="mt-4 h-1.5 rounded-full bg-recessed shadow-recessed"><div className="h-full w-2/3 rounded-full bg-accent"/></div></IndustrialPanel>})}</div>
  <div className="mt-6 grid gap-6 xl:grid-cols-[1.5fr_.7fr]"><IndustrialPanel className="overflow-hidden p-0"><div className="flex items-center justify-between border-b border-slate/15 px-5 py-4"><div><TechnicalLabel>RECENT WORKSPACES</TechnicalLabel><h2 className="mt-1 text-lg font-extrabold">Bid review queue</h2></div><Link href="/app/projects" className="text-xs font-bold text-accent">VIEW ALL <ArrowRight size={13} className="inline"/></Link></div>{loading?<div className="p-10 text-center text-sm text-slate">Loading workspaces…</div>:projects.length===0?<div className="p-12 text-center"><FolderOpen className="mx-auto text-slate" size={28}/><p className="mt-3 font-bold">No reviews yet.</p><p className="mt-1 text-xs text-slate">Create a workspace and upload a tender PDF.</p></div>:projects.slice(0,7).map(p=>{const s=summaries[p.id];return <Link href={`/app/projects/${p.id}`} key={p.id} className="grid gap-3 border-b border-slate/10 px-5 py-4 transition hover:bg-white/40 sm:grid-cols-[1fr_150px_100px_22px] sm:items-center"><div className="min-w-0"><p className="truncate text-sm font-extrabold">{p.name}</p><p className="mt-1 truncate text-[11px] text-slate">{p.gem_tender_id||p.description||'GeM bid review'}</p></div><div className="text-xs font-mono text-slate">{s?`${s.evaluated_requirements}/${s.total_requirements} EVALUATED`:'NOT ANALYZED'}</div><div><span className={`technical text-[9px] font-bold ${s?.risk_level==='high'?'text-red-600':s?.risk_level==='medium'?'text-amber-600':s?'text-emerald-700':'text-slate'}`}>{s?s.risk_level:'PENDING'}</span></div><ArrowRight size={15} className="text-slate"/></Link>})}</IndustrialPanel>
  <div className="space-y-6"><IndustrialPanel className="p-6"><div className="flex items-center justify-between"><TechnicalLabel>DECISION READINESS</TechnicalLabel><StatusLED status="online"/></div><h2 className="mt-2 text-xl font-extrabold">Review posture</h2><div className="mt-7 space-y-4">{[['Evidence available',totals.ok,'emerald'],['Needs officer attention',totals.attention,'amber'],['High-risk workspaces',totals.high,'red']].map(([l,v,c])=><div key={l as string} className="industrial-recessed rounded-xl p-4"><div className="flex justify-between"><span className="text-xs font-bold text-slate">{l as string}</span><span className={`font-mono text-lg font-bold ${c==='red'?'text-red-600':c==='amber'?'text-amber-600':'text-emerald-700'}`}>{v as number}</span></div></div>)}</div></IndustrialPanel><Link href="/app/chat" className="industrial-panel block rounded-2xl p-6 transition hover:-translate-y-1"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-chassis shadow-floating"><Activity size={19} className="text-accent"/></div><div><TechnicalLabel>PAIR ASSISTANT</TechnicalLabel><p className="mt-1 text-sm font-extrabold">Ask about a tender or evidence.</p></div></div></Link></div></div>
 </div>
}
