'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {motion} from 'framer-motion';
import {ArrowRight,ClipboardCheck,Plus,RefreshCw,Search} from 'lucide-react';
import {apiFetch} from '@/lib/api';
import {IndustrialPanel,TechnicalLabel} from '@/components/ui/industrial';
import {Project,Summary} from '@/lib/types';

export default function ProjectsPage(){
 const [projects,setProjects]=useState<Project[]>([]);const [summaries,setSummaries]=useState<Record<number,Summary>>({});const [name,setName]=useState('');const [tender,setTender]=useState('');const [query,setQuery]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');
 async function load(){setLoading(true);try{const d=await apiFetch<{projects:Project[]}>('/api/v1/projects');setProjects(d.projects);const pairs=await Promise.all(d.projects.map(async p=>{try{return [p.id,await apiFetch<Summary>(`/api/v1/compliance/projects/${p.id}/summary`)] as const}catch{return [p.id,null] as const}}));setSummaries(Object.fromEntries(pairs.filter((x):x is [number,Summary]=>!!x[1])))}catch(e){setError(e instanceof Error?e.message:'Unable to load projects.')}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 async function create(e:FormEvent){e.preventDefault();if(!name.trim())return;setBusy(true);setError('');try{const p=await apiFetch<Project>('/api/v1/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:name.trim(),description:'GeM bid compliance review workspace',gem_tender_id:tender.trim()||null})});window.location.href=`/app/projects/${p.id}`}catch(e){setError(e instanceof Error?e.message:'Unable to create workspace.')}finally{setBusy(false)}}
 const filtered=useMemo(()=>projects.filter(p=>`${p.name} ${p.gem_tender_id||''} ${p.status}`.toLowerCase().includes(query.toLowerCase())),[projects,query]);
 return <div className="mx-auto max-w-[1450px] px-4 py-6 md:px-7 md:py-8"><div className="flex items-end justify-between gap-4"><div><TechnicalLabel>WORKSPACE / BID REVIEWS</TechnicalLabel><h1 className="mt-2 text-4xl font-extrabold tracking-[-.04em]">Bid Reviews</h1><p className="mt-2 max-w-2xl text-sm text-slate">Create a review chassis for each tender. Requirements, evidence and compliance stay together.</p></div><button onClick={load} className="industrial-button rounded-xl bg-chassis p-3" aria-label="Refresh"><RefreshCw size={17}/></button></div>
 <IndustrialPanel className="mt-7 p-6"><div className="flex items-center gap-3"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-chassis shadow-floating"><Plus size={19} className="text-accent"/></div><div><TechnicalLabel>NEW REVIEW</TechnicalLabel><h2 className="mt-1 text-lg font-extrabold">Mount a new tender workspace</h2></div></div><form onSubmit={create} className="mt-6 grid gap-4 lg:grid-cols-[1fr_280px_auto]"><input className="industrial-input" required value={name} onChange={e=>setName(e.target.value)} placeholder="Tender / procurement name"/><input className="industrial-input" value={tender} onChange={e=>setTender(e.target.value)} placeholder="GeM Tender ID (optional)"/><button disabled={busy} className="industrial-button industrial-button-accent rounded-xl px-6 font-extrabold">{busy?'CREATING…':'CREATE REVIEW'}</button></form>{error&&<p className="mt-4 rounded-xl bg-red-50 px-4 py-3 text-sm font-semibold text-red-700">{error}</p>}</IndustrialPanel>
 <div className="mt-8 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><TechnicalLabel>ALL WORKSPACES</TechnicalLabel><p className="mt-1 text-xs text-slate">{projects.length} review{projects.length===1?'':'s'}</p></div><div className="industrial-recessed flex w-full items-center gap-2 rounded-xl px-3 sm:w-72"><Search size={16} className="text-slate"/><input value={query} onChange={e=>setQuery(e.target.value)} className="h-10 w-full bg-transparent text-xs outline-none" placeholder="Search reviews…"/></div></div>
 <div className="mt-4 space-y-4">{loading?<div className="py-16 text-center text-sm text-slate">Loading workspaces…</div>:filtered.length===0?<div className="industrial-panel p-14 text-center"><ClipboardCheck className="mx-auto text-slate" size={28}/><p className="mt-3 font-bold">No matching reviews.</p></div>:filtered.map((p,i)=>{const s=summaries[p.id];return <motion.div key={p.id} initial={{opacity:0,y:10}} animate={{opacity:1,y:0}} transition={{delay:i*.04}}><Link href={`/app/projects/${p.id}`} className="industrial-panel group grid gap-5 rounded-2xl p-5 transition hover:-translate-y-1 md:grid-cols-[1.4fr_.8fr_.45fr_.35fr] md:items-center"><div><div className="flex items-center gap-3"><span className="flex h-9 w-9 items-center justify-center rounded-lg bg-chassis shadow-recessed"><ClipboardCheck size={16} className="text-accent"/></span><div className="min-w-0"><h2 className="truncate text-sm font-extrabold">{p.name}</h2><p className="mt-1 truncate text-[11px] text-slate">{p.description||'GeM bid compliance review'}</p></div></div></div><div><TechnicalLabel>GEM ID</TechnicalLabel><p className="mt-1 truncate font-mono text-xs">{p.gem_tender_id||'—'}</p></div><div><TechnicalLabel>SCORE</TechnicalLabel><p className="mt-1 font-mono text-xl font-bold">{s?`${s.compliance_score}%`:'—'}</p></div><div className="flex items-center justify-between md:justify-end"><span className={`technical text-[9px] font-bold ${s?.risk_level==='high'?'text-red-600':s?.risk_level==='medium'?'text-amber-600':s?'text-emerald-700':'text-slate'}`}>{s?.risk_level||'PENDING'}</span><ArrowRight className="ml-3 text-slate transition group-hover:translate-x-1" size={17}/></div></Link></motion.div>})}</div>
 </div>
}
