import { Project, AIModel, Activity } from './types';

export const mockProjects: Project[] = [
  {
    id: '1',
    name: 'Expense Management SaaS',
    description: 'Full-stack expense tracking application with authentication',
    status: 'completed',
    progress: 100,
    lastUpdated: '2 hours ago',
    createdAt: '2024-01-15',
    models: ['Claude', 'GPT', 'Gemini'],
    tasks: [
      {
        id: 1,
        title: 'Requirements Analysis',
        description: 'Understanding project requirements',
        status: 'completed',
        executionTime: 120,
        tokens: 2500,
      },
      {
        id: 2,
        title: 'System Architecture',
        description: 'Designing system architecture',
        status: 'completed',
        assignedModel: 'Claude',
        executionTime: 180,
        tokens: 4200,
      },
      {
        id: 3,
        title: 'Frontend Development',
        description: 'Building React components',
        status: 'completed',
        assignedModel: 'GPT',
        executionTime: 420,
        tokens: 8900,
      },
      {
        id: 4,
        title: 'Backend Development',
        description: 'Implementing API endpoints',
        status: 'completed',
        assignedModel: 'Claude',
        executionTime: 480,
        tokens: 10200,
      },
      {
        id: 5,
        title: 'Database Schema',
        description: 'Creating PostgreSQL schema',
        status: 'completed',
        executionTime: 90,
        tokens: 1800,
      },
      {
        id: 6,
        title: 'Testing',
        description: 'Running test suite',
        status: 'completed',
        executionTime: 240,
        tokens: 3400,
      },
      {
        id: 7,
        title: 'Deployment',
        description: 'Deploying to Vercel',
        status: 'completed',
        executionTime: 60,
        tokens: 800,
      },
    ],
  },
  {
    id: '2',
    name: 'Data Pipeline Tool',
    description: 'ETL pipeline for analytics data processing',
    status: 'running',
    progress: 65,
    lastUpdated: '10 minutes ago',
    createdAt: '2024-01-14',
    models: ['Claude', 'DeepSeek'],
    tasks: [
      {
        id: 1,
        title: 'Data Source Analysis',
        status: 'completed',
        executionTime: 150,
      },
      {
        id: 2,
        title: 'Pipeline Architecture',
        status: 'completed',
        executionTime: 200,
      },
      {
        id: 3,
        title: 'ETL Implementation',
        status: 'running',
        assignedModel: 'Claude',
      },
      {
        id: 4,
        title: 'Testing & Validation',
        status: 'waiting',
      },
    ],
  },
  {
    id: '3',
    name: 'Mobile App Backend',
    description: 'REST API for iOS/Android application',
    status: 'planning',
    progress: 25,
    lastUpdated: '1 hour ago',
    createdAt: '2024-01-10',
    models: ['GPT'],
    tasks: [
      {
        id: 1,
        title: 'API Specification',
        status: 'running',
        assignedModel: 'GPT',
      },
      {
        id: 2,
        title: 'Database Design',
        status: 'waiting',
      },
    ],
  },
];

export const mockModels: AIModel[] = [
  {
    id: 'claude',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    status: 'connected',
    capabilities: ['Reasoning', 'Coding', 'Analysis', 'Writing'],
    contextWindow: '200k',
    usage: 15600,
    costPer1kTokens: 0.003,
  },
  {
    id: 'gpt',
    name: 'GPT-4 Turbo',
    provider: 'OpenAI',
    status: 'connected',
    capabilities: ['Coding', 'Review', 'Vision', 'Analysis'],
    contextWindow: '128k',
    usage: 12300,
    costPer1kTokens: 0.01,
  },
  {
    id: 'gemini',
    name: 'Gemini 2.0 Pro',
    provider: 'Google',
    status: 'connected',
    capabilities: ['Research', 'Vision', 'Analysis', 'Real-time'],
    contextWindow: '2m',
    usage: 8900,
    costPer1kTokens: 0.0015,
  },
  {
    id: 'deepseek',
    name: 'DeepSeek-V3',
    provider: 'DeepSeek',
    status: 'connected',
    capabilities: ['Reasoning', 'Math', 'Logic', 'Analysis'],
    contextWindow: '128k',
    usage: 5600,
    costPer1kTokens: 0.0008,
  },
  {
    id: 'grok',
    name: 'Grok-2',
    provider: 'xAI',
    status: 'not_connected',
    capabilities: ['Real-time', 'Reasoning', 'Retrieval'],
    contextWindow: '128k',
    usage: 0,
    costPer1kTokens: 0.002,
  },
  {
    id: 'mistral',
    name: 'Mistral Large',
    provider: 'Mistral AI',
    status: 'not_connected',
    capabilities: ['Coding', 'Multilingual', 'Analysis'],
    contextWindow: '128k',
    usage: 0,
    costPer1kTokens: 0.0024,
  },
];

export const mockActivity: Activity[] = [
  {
    id: '1',
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    message: 'Claude completed backend architecture design',
    model: 'Claude',
    projectId: '1',
    type: 'success',
  },
  {
    id: '2',
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    message: 'GPT started frontend component development',
    model: 'GPT',
    projectId: '1',
    type: 'info',
  },
  {
    id: '3',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    message: 'Gemini completed research phase',
    model: 'Gemini',
    projectId: '1',
    type: 'success',
  },
  {
    id: '4',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    message: 'Data Pipeline project created',
    projectId: '2',
    type: 'info',
  },
  {
    id: '5',
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    message: 'DeepSeek detected test failure, starting repair',
    model: 'DeepSeek',
    projectId: '2',
    type: 'warning',
  },
];
